projects/urls.py
from django.conf.urls import url

from . import views

app_name = 'projects'

urlpatterns = [
    url(r"^$", views.MainTasks.as_view(), name="all"),
    url(r'^ajax_tasks/', views.ajax_tasks, name="ajax_tasks"),
    url(r"^add/", views.AddTask.as_view(), name="addtask"),
    url(r"^edit/(?P<pk>\d+)/$", views.EditTask.as_view(), name="edittask"),
    url(r"^assign/(?P<pk>\d+)/$", views.assigntask, name="assigntask"),
    #url(r"^time/(?P<task_id>\d+)/$", views.TimeTask.as_view(), name="timetask"),
    url(r"^time/(?P<task_id>\d+)/$", views.ajax_timelog, name="timetask"),
]

tm/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import url, include
from django.views.generic import TemplateView
from . import views


urlpatterns = [
    url(r'^$',views.HomePage.as_view(), name='home'),
    url(r"^admin/", admin.site.urls),
    url(r'^bootstrap/$', TemplateView.as_view(template_name='boostrap_test.html')),
    url(r"^accounts/", include("accounts.urls", namespace="accounts")),
    #url(r"^accounts/", include("django.contrib.auth.urls")),
    url(r"^projects/", include("projects.urls",namespace='projects')),

]

if settings.DEBUG:
    import debug_toolbar
    from django.conf.urls.static import static
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
        #static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
    ] + urlpatterns

projects/models.py
from django.conf import settings
from django.db.models import Q, Sum, Count, FilteredRelation, Case, When
from django.urls import reverse
from django.db import models
from datetime import datetime, date, time
import calendar
from django.utils.text import slugify
from django.core.validators import MinValueValidator
import django.contrib.auth
from decimal import Decimal
import numpy as np
from tm.utils import deprecated
from .managers import TaskModelManager, TimeLogModelManager, TaskAssignmentQuerySet
from django.db.models.signals import pre_save, post_save
# from accounts.models import User
from django.contrib.auth import get_user_model
import os
#from django.contrib.auth.models import User

User = django.contrib.auth.get_user_model()


######################### MASTER DATA ###########################################

class MasterClient(models.Model):
    name                            = models.CharField(max_length=50, unique=True)
    contact                         = models.CharField(max_length=50, blank=True)
    phone                           = models.CharField(max_length=50, blank=True)
    owner                           = models.ForeignKey(User, on_delete=models.PROTECT,related_name='ownerscalendar')
    created_by                      = models.ForeignKey(User, on_delete=models.PROTECT,related_name='creatorscalendar')
    created_date                    = models.DateField(auto_now_add=True, blank=True)
    last_modified_by                = models.ForeignKey(User, on_delete=models.PROTECT,related_name='modifierscalendar')
    last_modified_date              = models.DateField(auto_now_add=True, blank=True)
    last_contact_date               = models.DateField(null=True, blank=True)
    required_contact_days           = models.IntegerField()
    active                          = models.BooleanField(default=True)
    billable                        = models.BooleanField(default=True)
    slug                            = models.SlugField(max_length=40)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Client'
        verbose_name_plural = 'Clients'

class MasterTaskType(models.Model):
    type                           = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.type

    class Meta:
        verbose_name = 'MasterTaskType'
        verbose_name_plural ='MasterTaskTypes'


class MasterTaskCategory(models.Model):
    category                         = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.category

    class Meta:
        verbose_name = 'MasterTaskCategory'
        verbose_name_plural ='MasterTaskCategory'

class MasterTaskStatus(models.Model):
    status                      = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.status

    class Meta:
        verbose_name = 'MasterTaskType'
        verbose_name_plural ='MasterTaskTypes'

#Posssible future implementation
class MasterBillingCalendar(models.Model):
    user                         = models.ForeignKey(User, on_delete=models.PROTECT,related_name='billingcalendar')
    calendar_month               = models.CharField(max_length=6,null=False, blank=False, unique=True)
    closed_date                  = models.DateField(null=True)
    closed_period                = models.BooleanField(default=False)
    start_date                   = models.DateField(null=True)
    end_date                     = models.DateField(null=True)
        #create standard calendar
    def __str__(self):
        return calendar_month

#######################################  PROJECT MODELS ########################################################

# Represents and Engagement or Case Number
class Project(models.Model):
    name                            = models.CharField(
                                            max_length=100,
                                            unique=True,
                                            error_messages={
                                                "unique": "An engagement with this name already exists, the engagement name must  be unique"
                                                })
    client                          = models.ForeignKey(MasterClient,on_delete=models.PROTECT, related_name='clientprojects')
    owner                           = models.ForeignKey(User, on_delete=models.PROTECT,related_name='ownersprojects') # Specific Owner for Project
    created_by                      = models.ForeignKey(User, on_delete=models.PROTECT,related_name='creatorsprojects')
    created_date                    = models.DateField(auto_now_add=True, blank=True)
    billable                        = models.BooleanField(default=True)
    last_modified_by                = models.ForeignKey(User, on_delete=models.PROTECT,related_name='modifiersprojects')
    last_modified_date              = models.DateField(auto_now_add=True, blank=True)
    project_start_date              = models.DateField(auto_now_add=True, blank=True)
    #assigned_users                  = models.ManyToManyField(User,related_name='usersassigned',through='projectuser') ##is this a real field?
    due_date                        = models.DateTimeField(blank=True,null=True)
    budgeted_hrs                    = models.DecimalField(max_digits=8, decimal_places=2,validators=[MinValueValidator(Decimal('0.00'))])
    last_contact_date               = models.DateField(null=True, blank=True)
    required_contact_days           = models.IntegerField()
    comments                        = models.TextField(blank=True, default='')
    completed_date                  = models.DateField(blank=True,null=True)
    active                          = models.BooleanField(default=True)
    slug                            = models.SlugField(max_length=40)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Project'
        verbose_name_plural = 'Projects'

    def project_model_pre_save_reciever(sender,instance,*args,**kwargs):
        print("before save")
        if not instance.slug and instance.name:
            instance.slug = slugify(instance.name)
            pre_save.connect(project_model_pre_save_reciever,sender=Project)

#Possible add on feature to allow only control user access to specific cases.
class ProjectUser(models.Model):

    project                         = models.ForeignKey(Project, on_delete=models.PROTECT, default='Unassigned',related_name='projects')
    user                            = models.ForeignKey(User,on_delete=models.PROTECT,related_name='projectusers')

    def __str__(self):
        return "Project: {project}".format(project=self.project.name)

    class Meta:
        verbose_name = 'ProjectUser'
        verbose_name_plural ='ProjectUserAssigned'
        unique_together = ("project", "user")

##Possible consideration of ability to subtask a task.  Recursive approach.
class Task(models.Model):

    SOURCES = (
        ('U', 'UserCreated'),
        ('A', 'Assigned'),
    )

    subject                         = models.CharField(max_length=40)
    parent                          = models.IntegerField(blank=True, null=True)  # Default this as the top_level_id of the task we are working on, allowing for the ability to recurivesly look at original tasks for a subtask much faster.
    project                         = models.ForeignKey(Project, on_delete=models.PROTECT,related_name='projecttasks')
    source_of_entry                 = models.CharField(max_length=1, choices=SOURCES, blank=True)
    billable                        = models.BooleanField(default=True)
    owner                           = models.ForeignKey(User, on_delete=models.PROTECT,related_name='taskowner',blank=True, null=True)
    created_by                      = models.ForeignKey(User, on_delete=models.PROTECT,related_name='taskcreator')
    created_date                    = models.DateTimeField(auto_now_add=True, blank=True)
    last_modified_by                = models.ForeignKey(User, on_delete=models.PROTECT,related_name='taskmodifier', blank=True, null=True)
    last_modified_date              = models.DateTimeField(blank=True, null=True, auto_now_add=True)
    category                        = models.ForeignKey(MasterTaskCategory, on_delete=models.PROTECT,related_name='tasktype', blank=True, null=True)
    type                            = models.ForeignKey(MasterTaskType, on_delete=models.PROTECT,related_name='tasktype')
    description                     = models.TextField(blank=True, max_length=300, default='')
    due_date                        = models.DateField(blank=True, null=True)
    status                          = models.ForeignKey(MasterTaskStatus, on_delete=models.PROTECT,related_name='taskstatus',blank=True, null=True,)
    budgeted_hrs                    = models.DecimalField(max_digits=8, decimal_places=2,validators=[MinValueValidator(Decimal('0.00'))])
    completed_date                  = models.DateTimeField(blank=True, null=True)
    active                          = models.BooleanField(default=True)

    def __str__(self):
        return str(self.pk)

    class Meta:
        verbose_name = 'Task'
        verbose_name_plural ='Tasks'

    objects = TaskModelManager()      #original Default models.Manager()

    unique_together = ('project','subject')

    def save(self, *args, **kwargs):
        if not self.pk:
            print ("This is a new record")
            super(Task,self).save(args, kwargs)
            print ("Now it has a PK of " + str(self.id))
            self.taskassigned.create(user_assigned=self.created_by,user_assigned_by=self.created_by)
            print ("Task has been assigned")
        else:
            print ("Record Edited " + str(self.id))
            super(Task,self).save(args, kwargs)

projects/forms.py
from django import forms
from projects import models

class TaskForm(forms.ModelForm):

    due_date = forms.DateField(widget=forms.SelectDateWidget(empty_label=("Nothing"),),)
    desciption = forms.CharField(widget=forms.Textarea)

    class Meta:
        model = models.Task
        fields = ['project','subject','billable','type','description','due_date','budgeted_hrs','created_by']

        labels = {
            'project': 'Case Name',
            'subject': 'Subject',
            'bilable': 'Billable',
            'type': 'Task Type',
            'description': 'Notes',
            'due_date': 'Date Due',
            'budgeted_hrs':'Budgeted Hours',
            'created_by': 'Created By',
        }

    def __init__(self, *args, **kwargs):
        super(TaskForm, self).__init__(*args,**kwargs)

class AssignTaskForm(forms.ModelForm):

    due_date = forms.DateField(widget=forms.SelectDateWidget(empty_label=("Nothing"),),)

    class Meta:
        model = models.TaskAssignment
        fields = ['user_assigned','due_date']

        labels = {
            'user_assigned': 'Assigned To',
            'due_date': 'Assignment Due Date',
        }

    def __init__(self, *args, **kwargs):
        super(AssignTaskForm, self).__init__(*args,**kwargs)
        #self.fields['description'].widget = forms.TextArea()

projects/views.py
from django.contrib import messages
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import(
    LoginRequiredMixin,
    PermissionRequiredMixin
)

from django.urls import reverse, reverse_lazy
from django.db import IntegrityError
from django.shortcuts import get_object_or_404
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.core import serializers
from django.core.serializers.json import DjangoJSONEncoder
from accounts.models import MyUser
from django.http import JsonResponse
from . import forms
import json
from .models import (
        Project,
        ProjectUser,
        Task,
        MasterClient,
        TimeLog,
        TaskAssignment
)


class MainTasks(LoginRequiredMixin, generic.TemplateView):
    template_name = 'projects/tasks.html'


@login_required
def ajax_tasks(request):
    if request.is_ajax():
        print ("Ajax call made")
        currentuser = request.user
        qs = Task.objects.get_assigned(currentuser.id).tasks_with_totalhrs(currentuser.id)
        return JsonResponse(list(qs),safe=False)
    else:
        return HttpReponse("Bad Response")


class AddTask(LoginRequiredMixin, generic.CreateView):
    template_name = 'projects/_addtaskform.html'
    form_class = forms.TaskForm
    success_url = reverse_lazy('projects:all')

    #sets initial values for a form
    def get_initial(self):
        initial = super(AddTask, self).get_initial()
        initial['created_by'] =self.request.user.id
        return initial


class EditTask(LoginRequiredMixin, generic.UpdateView):
    template_name = 'projects/_edittaskform.html'
    form_class = forms.TaskForm
    model = Task
    success_url = reverse_lazy('projects:all')


class AssignTask(LoginRequiredMixin, generic.DetailView):
    template_name = 'projects/_assigntaskform.html'
    model = TaskAssignment
    form_class = forms.AssignTaskForm
    success_url = reverse_lazy('projects:all')


@login_required
def assigntask(request,*args, **kwargs):
    if request.method == 'GET':
        print ('GET Request')
        pk = kwargs.get('pk')
        print (kwargs.get('pk'))
        assigned = TaskAssignment.objects.filter(task__id=pk).first()
        print (assigned.user_assigned)
        print (dir(assigned))
        data = {'user': assigned.user_assigned,
                'due_date': assigned.due_date,
                'form' : forms.AssignTaskForm
               }
        return render(request, template_name='projects/test.html', context=data)
    else:
        return HttpResponse("no response")


@login_required
def ajax_timelog(request,task_id):
    if request.is_ajax():
        print ("Ajax call made to timelog")
        currentuser = request.user
        task_number = task_id
        qs = TimeLog.objects.filter(task=task_number)
        return JsonResponse(list(qs),safe=False)
    else:
        return render(request, template_name='projects/_timelog.html')


class TimeTask(LoginRequiredMixin, generic.ListView):
    template_name = 'projects/_timelog.html'
    context_object_name ='loggedtime'

    def get_queryset(self):
        task_number = self.kwargs['task_id']
        qs = TimeLog.objects.filter(task=task_number)
        return qs

projects/templates/projects/_addtaskform.html
{% load bootstrap3 %}

<div class="row">

<div class="col-md-4">
<div class="mx-auto">
  <div class="padding-top 10">

  </div>
   <h1> Add Task </h1>
</div>

    <form class='form-task-ajax' method="POST" action='{% url "projects:addtask" %}'> {% csrf_token %}
      {% bootstrap_form form %}
        <input type="submit" value="Add" class="btn btn-default">
    </form>
    </div>
      </div>

projects/templates/projects/_assigntaskform.html
{% load bootstrap3 %}

<div class="container">
    <h1>Update Task </h1>
    <form class='form-task-ajax' method="POST" action='{% url "projects:assigntask" pk=task.id %}'> {% csrf_token %}
      {% bootstrap_form form %}
        <input type="submit" value="Update" class="btn btn-default">
    </form>
</div>

projects/templates/projects/_edittaskform.html
{% load bootstrap3 %}

<div class="container">
    <h1>Update Task </h1>
    <form class='form-task-ajax' method="POST" action='{% url "projects:edittask" pk=task.id %}'> {% csrf_token %}
      {% bootstrap_form form %}
        <input type="submit" value="Update" class="btn btn-default">
    </form>
</div>

projects/templates/projects/_mainhours.html
<table class="table">
  <thead>
    <tr>
      <th scope="col">  </th>
      <th scope="col"> Worked Hours </th>
      <th scope="col"> Billed Hours </th>
      <th scope="col"> Required Hours </th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">Day</th>
      <td> {{ view.all_hrs }} </td>
      <td>{{ billedhrs_day }}</td>
      <td>"Coming Soon"</td>
    </tr>
    <tr>
      <th scope="row">Week</th>
      <td> </td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <th scope="row">Month</th>
      <td></td>
      <td></td>
      <td></td>
    </tr>
  </tbody>
</table>

projects/templates/projects/_stopwatch.html
{% load staticfiles %}


<link rel="stylesheet" type="text/css" href="{% static "css/stopwatch.css"  %}" />


<div id="wrapper">
	<div id="stopwatch">
		<p id="days">00</p>
		<span id="first-divider" class="divider">:</span>
		<p id="hours">00</p>
		<span id="second-divider" class="divider">:</span>
		<p id="minutes">00</p>
		<span id="third-divider" class="divider">:</span>
		<p id="seconds">00</p>
	</div>

	<div id="button-wrap">
		<button id="start"><i class="fa fa-play fa-fw" aria-hidden="true"></i>Start</button>
		<button id="pause"><i class="fa fa-pause fa-fw" aria-hidden="true"></i>Pause</button>
		<button id="resume"><i class="fa fa-play fa-fw" aria-hidden="true"></i>Resume</button>
		<button id="reset" class="no-text"><i class="fa fa-repeat fa-fw fa-flip-horizontal" aria-hidden="true"></i></button>
		<button id="stop" class="no-text"><i class="fa fa-stop fa-fw fa-flip-horizontal" aria-hidden="true"></i></button>
	</div>
</div>

<script>

var counter = 0;
var isPaused = true;

$("#pause, #resume").hide();
$("#days, #hours, #first-divider, #second-divider").hide();
$("#start").show();

var t = window.setInterval(function() {
	if (!isPaused) {
		counter++;
		var s = counter;
		convertSeconds(Math.floor(s));
	}
}, 1000);

// Button Click Events
$("#start").click(function () {
	startClock();
	$(this).hide();
	$("#pause").show();
	$("#reset, #stop").css("opacity", "1");
});

$("#pause").click(function (){
	pauseClock();
	$(this).hide();
	$("#resume").show();
});

$("#resume").click(function (){
	resumeClock();
	$(this).hide();
	$("#pause").show();
});

$("#reset").click(function (){
	resetClock();
	$("#resume").hide();
	$("#pause").show();
});

$("#stop").click(function () {
	resetClock();
	$("#pause, #resume").hide();
	$("#start").show();
	$("#reset, #stop").css("opacity", "0");
});


function startClock() {
	isPaused = false;
}
function pauseClock() {
	isPaused = true;
}
function resumeClock() { isPaused = false; }
function resetClock() {
	counter = 0;
	$("#days").html("00");
	$("#hours").html("00");
	$("#minutes").html("00");
	$("#seconds").html("00");
}
function stopClock() {
	resetClock();
	isPaused = true;
}

function convertSeconds(s) {
	var days = Math.floor(s / 86400)
	var hours = Math.floor((s % 86400) / 3600);
	var minutes = Math.floor(((s % 86400) % 3600) / 60);
	var seconds = ((s % 86400) % 3600) % 60;

	if (days		< 10) {days 	 = "0" + days}
	if (hours 	< 10) {hours 	 = "0" + hours;}
	if (minutes < 10) {minutes = "0" + minutes;}
	if (seconds < 10) {seconds = "0" + seconds;}

	$("#days").html(days);
	$("#hours").html(hours);
	$("#minutes").html(minutes);
	$("#seconds").html(seconds);

	if (days == 0 && hours == 0) {
		$("#days, #hours").hide();
		$("#first-divider, #second-divider").hide();
	} else if (days == 0) {
		$("#days").hide();
		$("#hours").show();
		$("#second-divider").show();
	} else {
		$("p, .divider").show();
	}
}
</script>

projects/templates/projects/_tasktabulator.html
<script>

var editIcon = function(cell, formatterParams){ //plain text value
    return "<i class='far fa-edit'></i>";
};

var timeIcon = function(cell, formatterParams){ //plain text value
    return "<i class='far fa-clock'></i>";
};

var assignIcon = function(cell, formatterParams){ //plain text value
    return "<i class='fas fa-user-edit'></i>";
};


var addtask = function(e, cell){
  var xhttp = new XMLHttpRequest();
  xhttp.onreadystatechange = function() {
   if (this.readyState == 4 && this.status == 200) {
    document.getElementById("panel").innerHTML = this.response;
   }
 };
 xhttp.open("GET", "/projects/add/", true);
 xhttp.send();
}

var edittask = function(e, cell){
  var xhttp = new XMLHttpRequest();
  xhttp.onreadystatechange = function() {
   if (this.readyState == 4 && this.status == 200) {
    document.getElementById("panel").innerHTML = this.response;
   }
 };
 xhttp.open("GET", "/projects/edit/"+cell.getRow().getData().id, true);
 xhttp.send();
}

var timetask = function(e, cell){
  var xhttp = new XMLHttpRequest();
  xhttp.onreadystatechange = function() {
   if (this.readyState == 4 && this.status == 200) {
    document.getElementById("panel").innerHTML = this.response;
   }
 };
 xhttp.open("GET", "/projects/time/"+cell.getRow().getData().id, true);
 xhttp.send();
}

var assigntask = function(e, cell){
  var xhttp = new XMLHttpRequest();
  xhttp.onreadystatechange = function() {
   if (this.readyState == 4 && this.status == 200) {
    document.getElementById("panel").innerHTML = this.response;
   }
 };
 xhttp.open("GET", "/projects/assign/"+cell.getRow().getData().id, true);
 xhttp.send();
}


//column definition in the columns array
  $("#task-table").tabulator({
    layout:"fitColumns",
    tooltips:true,
    movableRows: true,
    tooltipsHeader:true,
    addRowPos:"top",
    history:true,
    pagination:"local",
    paginationSize:10,
    movableColumns:true,
    resizableRows:true,
    initialSort:[
      {column:"name", dir:"asc"},
    ],
      columns:[
          {title:"Task Subject", field:"subject", sorter:"string", width:200},
          {title:"Client", field:"project__client__name", align:"left", width:100, headerFilter:"input", headerFilterPlaceholder:"filter client"},
          {title:"Type", field:"type__type", sorter:"text", align:"left", headerFilter:"input", headerFilterPlaceholder:"filter type"},
          {title:"Task Description", field:"description", sorter:"string", headerFilter:"input", headerFilterPlaceholder:"filter description"},
          {title:"Budgeted Hours", field:"budgeted_hrs", sorter:"string", align:"right", bottomCalc:"sum"},
          {title:"Due Date", field:"due_date", sorter:"date", align:"center",headerFilter:"input"},
          {title:"Last Client Contact", field:"project__last_contact_date", sorter:"date", align:"center",headerFilter:"input"},
          {formatter:editIcon, width:40, align:"center", cellClick:edittask},
          {formatter:timeIcon, width:40, align:"center", cellClick:timetask},
          {formatter:assignIcon, width:40, align:"center", cellClick:assigntask},
      ],

      //Research how to change the priority and post a request back to the server
      rowMoved:function(row){
        var rows = $("#task-table").tabulator("getRows", true)
        var position = $("#task-table").tabulator("getRowPosition", row)
        if (row.getData().priority !=0) {
          console.log("That worked")
          alert("Task ID: " + row.getData().id + " has been moved to position" + position);
        };
      },

      rowFormatter:function(row){
        var today = new Date();
        today.setHours(0,0,0,0);
        dueDateCell = row.getCell('due_date');
        console.log(dueDateCell);
        contactDateCell = row.getCell('project__last_contact_date');
        var data = row.getData(); //get data object for row
        contactdate = Date.parse(data.project__last_contact_date) || 0;
        duedate = Date.parse(data.due_date) || 0;
        console.log(duedate)

        if(contactdate <= today){
            //contactDateCell.getElement().css({"background-color":"red"}); //apply css change to row element
            console.log("Contact Date in the Past")
        };
        if(duedate <= today){
          dueDateCell.getElement().css({"background-color":"#FF6347"}); //apply css change to row element
          console.log("Due Date in the Past")
        };
    },
  });


  $("#task-table").tabulator("setData", '/projects/ajax_tasks/');



</script>

projects/templates/projects/_timelog.html
<h1> Time Logged for Task </h1>

<div class="table" id="timelog-panel" ></div>

<script>

var editIcon = function(cell, formatterParams){ //plain text value
    return "<i class='far fa-edit'></i>";
};


//column definition in the columns array
  $("#timelog-panel").tabulator({
    layout:"fitColumns",
    tooltips:true,
    movableRows: false,
    tooltipsHeader:true,
    addRowPos:"top",
    history:true,
    //pagination:"local",
    //paginationSize:10,
    movableColumns:false,
    resizableRows:false,
    initialSort:[
      {column:"name", dir:"asc"},
    ],
      columns:[
          {title:"Date Logged", field:"date_time_started", sorter:"string", width:200},
          {title:"Actual Hours", field:"actualhrs", sorter:"text", align:"right", bottomCalc:"sum"},
          {title:"Billable Hours", field:"billablehrs", sorter:"string", align:"right", bottomCalc:"sum"},
          {title:"Comments", field:"comments", sorter:"string", align:"left", bottomCalc:"sum"},
          {formatter:editIcon, width:40, align:"center", cellClick:edittask},

      ],

  });



  $("#timelog-panel").tabulator("setData", '/projects/ajax_tasks/16');


</script>

</div>

projects/templates/projects/_timelogtabulator.html
<script>

var editIcon = function(cell, formatterParams){ //plain text value
    return "<i class='far fa-edit'></i>";
};


//column definition in the columns array
  $("#main-panel").tabulator({
    layout:"fitColumns",
    tooltips:true,
    movableRows: false,
    tooltipsHeader:true,
    addRowPos:"top",
    history:true,
    //pagination:"local",
    //paginationSize:10,
    movableColumns:false,
    resizableRows:false,
    initialSort:[
      {column:"name", dir:"asc"},
    ],
      columns:[
          {title:"Date Logged", field:"date_time_started", sorter:"string", width:200},
          {title:"Actual Hours", field:"actualhrs", sorter:"text", align:"right", bottomCalc:"sum"},
          {title:"Billable Hours", field:"billablehrs", sorter:"string", align:"right", bottomCalc:"sum"},
          {title:"Comments", field:"comments", sorter:"string", align:"left", bottomCalc:"sum"},
          {formatter:editIcon, width:40, align:"center", cellClick:edittask},

      ],

  });



  $("#main-panel").tabulator("setData", '/projects/time/16');


</script>

projects/templates/projects/tasks.html
{% extends "base.html" %}

{% block content %}

<div class="welcome">

    <h1> Welcome {{ user.first_name }} {{ user.last_name }}  </h1>

</div>

<div class="main_tasks" id="task-table" ></div>
{% include "projects/_tasktabulator.html" %}

    <!--  {% include "projects/_stopwatch.html" %} -->

<div class="button-row">
    <button type="button" id='add-task-button' onclick="addtask()" class="btn btn-primary"> Add Task </button>
</div>

<div class='main-panel' id='panel'> </div>

{% endblock %}

projects/templates/projects/test.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1> This is our test template </h1>
    <h1>  {{ user }}</h1>
    <h1>  {{ due_date }}</h1>
    <p>

{{form}}     </p>
  </body>
</html>