accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'login/$', views.Login.as_view(),name='login'),
    url(r'logout/$', views.Logout.as_view(), name="logout"),
    url(r'register/$', views.Register.as_view(), name="register"),
]

projects/urls.py
from django.conf.urls import url

from . import views

app_name = 'projects'

urlpatterns = [
    url(r"^$", views.MainTasks.as_view(), name="all"),
    url(r'^ajax_tasks/', views.ajax_tasks, name="ajax_tasks"),
    url(r"^add/", views.AddTask.as_view(), name="addtask"),
    url(r"^edit/(?P<pk>\d+)/$", views.EditTask.as_view(), name="edittask"),
    url(r"^assign/(?P<pk>\d+)/$", views.assigntask, name="assigntask"),
    #url(r"^time/(?P<task_id>\d+)/$", views.TimeTask.as_view(), name="timetask"),
    url(r"^time/(?P<task_id>\d+)/$", views.ajax_timelog, name="timetask"),
]

tm/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import url, include
from django.views.generic import TemplateView
from . import views


urlpatterns = [
    url(r'^$',views.HomePage.as_view(), name='home'),
    url(r"^admin/", admin.site.urls),
    url(r'^bootstrap/$', TemplateView.as_view(template_name='boostrap_test.html')),
    url(r"^accounts/", include("accounts.urls", namespace="accounts")),
    #url(r"^accounts/", include("django.contrib.auth.urls")),
    url(r"^projects/", include("projects.urls",namespace='projects')),

]

if settings.DEBUG:
    import debug_toolbar
    from django.conf.urls.static import static
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
        #static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
    ] + urlpatterns

templates/_libraries.html
{% load staticfiles %}

        <!-- jquery -->

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="http://code.jquery.com/ui/1.12.1/jquery-ui.js"integrity="sha256-T0Vest3yCU7pafRw9r+settMBX6JkKN06dqBnpQ8d30="  crossorigin="anonymous"></script>

        <!-- bootstrap -->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

        <!-- fonts -->

        <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.12/css/all.css" integrity="sha384-G0fIWCsCzJIMAVNQPfjH08cyYaUtMwjJwqiRKxxE/rx96Uroj1BtIQ6MLJuheaO9" crossorigin="anonymous">


        <!--- Tabulator Libraries ---------->
       <link href="https://cdnjs.cloudflare.com/ajax/libs/tabulator/3.5.1/css/tabulator.min.css" rel="stylesheet">
       <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tabulator/3.5.1/js/tabulator.min.js"></script>
       <link href="https://cdnjs.cloudflare.com/ajax/libs/tabulator/3.5.1/css/tabulator_modern.css" rel="stylesheet">

       <!--- Static Files ---------->
       <link rel="stylesheet" type="text/css" href="{% static "css/mystyles.css"  %}" />

templates/_navbar.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
      <div class="container-cust">
        <div class='text-right'>


        <a class="navbar-brand mynav"> </a>
        <button class='navbar-toggler' type='button' data-toggle='collapse' data-target='#navbarCollapseLinks' aria-expanded='false' aria-label='Toggle Navigation'>
      <span class='navbar-toggler-icon'></span>
    </button>

    <div class='collapse navbar-collapse' id='navbarCollapseLinks'>
        <ul class='navbar-nav'>
            {% if user.is_authenticated %}
                  <li class='nav-item'>
                    <a href="{% url 'projects:all' %}"  class="btn btn-simple">Task Manager</a></li>
                  <li class='nav-item'>
                    <a href="{% url 'accounts:logout' %}" class="btn btn-simple">Log out</a></li>
                    <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Other Options
                    </a>
                    <div class="dropdown-menu dropdown-menu-left" aria-labelledby="navbarDropdownMenuLink">
                      <a class="dropdown-item" href="#">Action</a>
                      <a class="dropdown-item" href="#">Another action</a>
                      <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                  </li>
            {% else %}
                  <li class='nav-item'>
                    <a href="{% url 'accounts:login' %}" class="btn btn-simple">Log in</a></li>
                  <li class='nav-item'>
                    <a href="{% url 'accounts:register' %}" class="btn btn-simple">Register</a></li>
            {% endif %}


          </ul>
      </div>
      </div>
              </div>
    </nav>

templates/base.html
<!DOCTYPE html>

{% load staticfiles %}

<html>

  <head>
    <meta charset="utf-8">
    <title>Hourly Billing Helper</title>
    {% include "_libraries.html" %}
  </head>
  
{% include "_navbar.html" %}

  <div class="container-cust">
         <body>
          {% block content %}
          {% endblock %}
          </body>
      </div>
</html>

templates/boostrap_test.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">

      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <title>Practice Bootstrapping</title>
  </head>
  <body>
    <div class="container">

    <div class="text-right text-uppercase">
      <div class="">
        <h1 style="padding 200"> Text Right and uppercase </h1>
            </div>
        <h1> A header below the first header</h1>
    </div>
    <h2> Normal Text </h2>

  </div>
  </body>
</html>

templates/home.html
{% extends "base.html" %}
{% block content %}

<c
    <h1>Welcome to Hourly Billing Helper </h1>
    <h2>Login or Sign-up to get started!</h2>


{% endblock %}